import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding CarbonProof database...');

  // Clean existing database records
  await prisma.anomalyEvent.deleteMany({});
  await prisma.verificationStep.deleteMany({});
  await prisma.satelliteSnapshot.deleteMany({});
  await prisma.telemetryPoint.deleteMany({});
  await prisma.credit.deleteMany({});
  await prisma.project.deleteMany({});
  await prisma.user.deleteMany({});

  // 1. Seed Demo Accounts
  await prisma.user.createMany({
    data: [
      {
        email: 'buyer@carbonproof.io',
        name: 'Elena Rostova (ESG Fund Buyer)',
        role: 'BUYER',
        password: 'password123',
      },
      {
        email: 'auditor@carbonproof.io',
        name: 'Dr. Marcus Vance (Chief Auditor)',
        role: 'AUDITOR',
        password: 'password123',
      },
      {
        email: 'registry@carbonproof.io',
        name: 'Sarah Chen (Verra Market Registry)',
        role: 'REGISTRY',
        password: 'password123',
      },
    ],
  });

  // 2. Seed Projects Data (18 Total across 3 Regions)
  const projectsData = [
    // --- SOUTH AMERICA (6 Projects) ---
    {
      id: 'CP-AMZ-8841',
      name: 'Alto Mayo Rainforest Reserve',
      location: 'San Martín Region',
      country: 'Peru',
      latitude: -6.052,
      longitude: -77.165,
      region: 'S. America',
      type: 'Avoided Deforestation',
      areaHectares: 182400,
      riskScore: 96,
      trustStatus: 'VERIFIED',
      lastScanDate: '12 mins ago (Sentinel-2B)',
      canopyChangeRate: '+1.4% Biomass Density',
      carbonCreditsIssued: 450000,
      vintage: 2025,
      description: 'High-density tropical cloud forest ecosystem under continuous satellite SAR, multispectral monitoring, and canopy IoT sensor protection.',
      sensorMeshNodes: 142,
      droneSurveysCompleted: 38,
      traditionalAuditCost: 65000,
      traditionalAuditDays: 180,
      carbonProofCost: 2800,
      carbonProofSeconds: 4.2,
    },
    {
      id: 'CP-CDA-1102',
      name: 'Cordillera Azul National Park',
      location: 'Loreto & San Martín',
      country: 'Peru',
      latitude: -7.521,
      longitude: -75.984,
      region: 'S. America',
      type: 'Avoided Deforestation',
      areaHectares: 1350000,
      riskScore: 98,
      trustStatus: 'VERIFIED',
      lastScanDate: '5 mins ago (Sentinel-2B)',
      canopyChangeRate: '+0.4% Canopy Intactness',
      carbonCreditsIssued: 1200000,
      vintage: 2025,
      description: 'Massive mega-biodiversity mountain ridge rainforest barrier preventing illegal road access into pristine Amazon headwaters.',
      sensorMeshNodes: 210,
      droneSurveysCompleted: 64,
      traditionalAuditCost: 140000,
      traditionalAuditDays: 210,
      carbonProofCost: 4500,
      carbonProofSeconds: 4.8,
    },
    {
      id: 'CP-[#TMB]-5501',
      name: 'Tambopata Biodiversity Reserve',
      location: 'Madre de Dios',
      country: 'Peru',
      latitude: -12.931,
      longitude: -69.301,
      region: 'S. America',
      type: 'Avoided Deforestation',
      areaHectares: 275000,
      riskScore: 91,
      trustStatus: 'VERIFIED',
      lastScanDate: '28 mins ago (PlanetScope)',
      canopyChangeRate: '+0.8% Biomass Index',
      carbonCreditsIssued: 680000,
      vintage: 2025,
      description: 'Buffer zone protecting primary Amazonian rainforest against artisanal gold mining incursions.',
      sensorMeshNodes: 115,
      droneSurveysCompleted: 29,
      traditionalAuditCost: 75000,
      traditionalAuditDays: 165,
      carbonProofCost: 3100,
      carbonProofSeconds: 3.9,
    },
    {
      id: 'CP-JRI-9012',
      name: 'Jari Pará REDD+ Project',
      location: 'Pará State',
      country: 'Brazil',
      latitude: -0.854,
      longitude: -52.512,
      region: 'S. America',
      type: 'Reforestation',
      areaHectares: 310000,
      riskScore: 88,
      trustStatus: 'VERIFIED',
      lastScanDate: '45 mins ago (Sentinel-1 SAR)',
      canopyChangeRate: '+1.9% Canopy Density',
      carbonCreditsIssued: 820000,
      vintage: 2025,
      description: 'Sustainable agroforestry and native tree planting restoring degraded cattle pasture corridors.',
      sensorMeshNodes: 95,
      droneSurveysCompleted: 41,
      traditionalAuditCost: 85000,
      traditionalAuditDays: 190,
      carbonProofCost: 3400,
      carbonProofSeconds: 4.1,
    },
    {
      id: 'CP-SRI-3301',
      name: 'Suruí Indigenous Reforestation',
      location: 'Rondônia State',
      country: 'Brazil',
      latitude: -10.812,
      longitude: -61.421,
      region: 'S. America',
      type: 'Reforestation',
      areaHectares: 240000,
      riskScore: 64,
      trustStatus: 'ELEVATED RISK',
      lastScanDate: '1 hour ago (PlanetScope)',
      canopyChangeRate: '-2.1% Sector 3 Disturbance',
      carbonCreditsIssued: 410000,
      vintage: 2024,
      description: 'Indigenous territory protection project flagged due to localized peripheral illegal logging road construction.',
      sensorMeshNodes: 68,
      droneSurveysCompleted: 14,
      traditionalAuditCost: 60000,
      traditionalAuditDays: 150,
      carbonProofCost: 2200,
      carbonProofSeconds: 3.5,
    },
    {
      id: 'CP-TMC-4402',
      name: 'Tumucumaque Rainforest Sanctuary',
      location: 'Amapá State',
      country: 'Brazil',
      latitude: 1.842,
      longitude: -52.215,
      region: 'S. America',
      type: 'Avoided Deforestation',
      areaHectares: 890000,
      riskScore: 97,
      trustStatus: 'VERIFIED',
      lastScanDate: '18 mins ago (Sentinel-2B)',
      canopyChangeRate: '+0.3% Biomass Growth',
      carbonCreditsIssued: 1100000,
      vintage: 2025,
      description: 'Largest tropical forest national park on Earth under continuous multi-satellite SAR radar surveillance.',
      sensorMeshNodes: 180,
      droneSurveysCompleted: 52,
      traditionalAuditCost: 120000,
      traditionalAuditDays: 200,
      carbonProofCost: 4100,
      carbonProofSeconds: 4.6,
    },

    // --- AFRICA (6 Projects) ---
    {
      id: 'CP-KSG-4412',
      name: 'Kasigau Wildlife Corridor Protection',
      location: 'Taita-Taveta County',
      country: 'Kenya',
      latitude: -3.633,
      longitude: 38.65,
      region: 'Africa',
      type: 'Avoided Deforestation',
      areaHectares: 200000,
      riskScore: 89,
      trustStatus: 'VERIFIED',
      lastScanDate: '1 hour ago (PlanetScope)',
      canopyChangeRate: '-0.1% Natural Seasonal Dry',
      carbonCreditsIssued: 620000,
      vintage: 2024,
      description: 'Dryland acacia-commiphora forest sanctuary buffering biodiversity corridors between Tsavo East and West National Parks.',
      sensorMeshNodes: 110,
      droneSurveysCompleted: 45,
      traditionalAuditCost: 55000,
      traditionalAuditDays: 140,
      carbonProofCost: 2500,
      carbonProofSeconds: 3.8,
    },
    {
      id: 'CP-MND-7701',
      name: 'Mai Ndombe REDD+ Forest',
      location: 'Mai-Ndombe Province',
      country: 'DR Congo',
      latitude: -1.912,
      longitude: 18.283,
      region: 'Africa',
      type: 'Avoided Deforestation',
      areaHectares: 248000,
      riskScore: 92,
      trustStatus: 'VERIFIED',
      lastScanDate: '18 mins ago (Sentinel-1 SAR)',
      canopyChangeRate: '+0.9% Canopy Density',
      carbonCreditsIssued: 780000,
      vintage: 2025,
      description: 'Congo Basin primary rainforest protection protecting forest elephant habitat and dense peatland carbon stores.',
      sensorMeshNodes: 130,
      droneSurveysCompleted: 31,
      traditionalAuditCost: 80000,
      traditionalAuditDays: 175,
      carbonProofCost: 3200,
      carbonProofSeconds: 4.0,
    },
    {
      id: 'CP-CHY-8812',
      name: 'Chyulu Hills Cloud Forest',
      location: 'Makueni County',
      country: 'Kenya',
      latitude: -2.612,
      longitude: 37.892,
      region: 'Africa',
      type: 'Reforestation',
      areaHectares: 150000,
      riskScore: 95,
      trustStatus: 'VERIFIED',
      lastScanDate: '30 mins ago (Sentinel-2B)',
      canopyChangeRate: '+2.2% Tree Density',
      carbonCreditsIssued: 510000,
      vintage: 2025,
      description: 'Volcanic mountain ridge mist forest restoration supplying vital watershed services to downstream communities.',
      sensorMeshNodes: 90,
      droneSurveysCompleted: 35,
      traditionalAuditCost: 48000,
      traditionalAuditDays: 130,
      carbonProofCost: 2100,
      carbonProofSeconds: 3.6,
    },
    {
      id: 'CP-GLA-2201',
      name: 'Gola Rainforest Conservation',
      location: 'Eastern Province',
      country: 'Sierra Leone',
      latitude: 7.512,
      longitude: -10.842,
      region: 'Africa',
      type: 'Avoided Deforestation',
      areaHectares: 70000,
      riskScore: 93,
      trustStatus: 'VERIFIED',
      lastScanDate: '22 mins ago (PlanetScope)',
      canopyChangeRate: '+0.6% Biomass Growth',
      carbonCreditsIssued: 340000,
      vintage: 2025,
      description: 'Upper Guinean tropical rainforest hotspot protecting pygmy hippos and endemic primates.',
      sensorMeshNodes: 75,
      droneSurveysCompleted: 22,
      traditionalAuditCost: 42000,
      traditionalAuditDays: 120,
      carbonProofCost: 1900,
      carbonProofSeconds: 3.4,
    },
    {
      id: 'CP-KRB-6601',
      name: 'Kariba REDD+ Woodland Project',
      location: 'Lake Kariba Basin',
      country: 'Zimbabwe',
      latitude: -17.215,
      longitude: 27.842,
      region: 'Africa',
      type: 'Avoided Deforestation',
      areaHectares: 785000,
      riskScore: 58,
      trustStatus: 'ELEVATED RISK',
      lastScanDate: '15 mins ago (MODIS Fire Stream)',
      canopyChangeRate: '-3.4% Fuelwood Cutting',
      carbonCreditsIssued: 950000,
      vintage: 2024,
      description: 'Miombo woodland corridor currently flagged for unauthorized firewood harvesting and buffer zone fires.',
      sensorMeshNodes: 85,
      droneSurveysCompleted: 18,
      traditionalAuditCost: 95000,
      traditionalAuditDays: 190,
      carbonProofCost: 3800,
      carbonProofSeconds: 4.4,
    },
    {
      id: 'CP-ELG-1105',
      name: 'Mount Elgon Watershed Restoration',
      location: 'Eastern Region',
      country: 'Uganda',
      latitude: 1.152,
      longitude: 34.542,
      region: 'Africa',
      type: 'Reforestation',
      areaHectares: 110000,
      riskScore: 94,
      trustStatus: 'VERIFIED',
      lastScanDate: '40 mins ago (Sentinel-2B)',
      canopyChangeRate: '+2.7% Agroforestry Expansion',
      carbonCreditsIssued: 420000,
      vintage: 2025,
      description: 'High-altitude montane forest agroforestry planting buffering coffee smallholders against landslides.',
      sensorMeshNodes: 82,
      droneSurveysCompleted: 27,
      traditionalAuditCost: 45000,
      traditionalAuditDays: 125,
      carbonProofCost: 2000,
      carbonProofSeconds: 3.5,
    },

    // --- SOUTHEAST ASIA (6 Projects) ---
    {
      id: 'CP-RMB-3011',
      name: 'Rimba Raya Peatland Sanctuary',
      location: 'Central Kalimantan',
      country: 'Indonesia',
      latitude: -2.852,
      longitude: 112.35,
      region: 'SE Asia',
      type: 'Peatland Conservation',
      areaHectares: 64000,
      riskScore: 68,
      trustStatus: 'ELEVATED RISK',
      lastScanDate: '42 mins ago (MODIS Fire Stream)',
      canopyChangeRate: '-1.8% Sector 7 Small Clearing',
      carbonCreditsIssued: 520000,
      vintage: 2024,
      description: 'Critical tropical peat swamp forest habitat protecting wild orangutan populations. Currently flagged due to localized peripheral agricultural clearing.',
      sensorMeshNodes: 76,
      droneSurveysCompleted: 19,
      traditionalAuditCost: 52000,
      traditionalAuditDays: 135,
      carbonProofCost: 2300,
      carbonProofSeconds: 3.7,
    },
    {
      id: 'CP-MNG-9912',
      name: 'Delta Blue Carbon Mangrove Belt',
      location: 'Indus River Delta',
      country: 'Pakistan',
      latitude: 24.128,
      longitude: 67.452,
      region: 'SE Asia',
      type: 'Mangrove Restoration',
      areaHectares: 95000,
      riskScore: 94,
      trustStatus: 'VERIFIED',
      lastScanDate: '32 mins ago (Landsat 9)',
      canopyChangeRate: '+2.8% Blue Carbon Sequestration',
      carbonCreditsIssued: 310000,
      vintage: 2025,
      description: 'Coastal tidal wetland sequestration engine monitored via synthetic aperture radar (SAR) to penetrate cloud cover and track saline mudflat mangrove expansion.',
      sensorMeshNodes: 98,
      droneSurveysCompleted: 24,
      traditionalAuditCost: 48000,
      traditionalAuditDays: 130,
      carbonProofCost: 2100,
      carbonProofSeconds: 3.5,
    },
    {
      id: 'CP-KTG-7712',
      name: 'Katingan Mentaya Peatland Project',
      location: 'Central Kalimantan',
      country: 'Indonesia',
      latitude: -2.412,
      longitude: 113.125,
      region: 'SE Asia',
      type: 'Peatland Conservation',
      areaHectares: 150000,
      riskScore: 97,
      trustStatus: 'VERIFIED',
      lastScanDate: '8 mins ago (Sentinel-1 SAR)',
      canopyChangeRate: '+0.5% Peat Water Table Stability',
      carbonCreditsIssued: 1400000,
      vintage: 2025,
      description: 'Global benchmark peat swamp REDD+ project protecting deep carbon-rich peat soils and high endangered species density.',
      sensorMeshNodes: 160,
      droneSurveysCompleted: 58,
      traditionalAuditCost: 110000,
      traditionalAuditDays: 195,
      carbonProofCost: 4200,
      carbonProofSeconds: 4.5,
    },
    {
      id: 'CP-KEO-8802',
      name: 'Keo Seima Wildlife Sanctuary',
      location: 'Mondulkiri Province',
      country: 'Cambodia',
      latitude: 12.215,
      longitude: 106.942,
      region: 'SE Asia',
      type: 'Avoided Deforestation',
      areaHectares: 290000,
      riskScore: 90,
      trustStatus: 'VERIFIED',
      lastScanDate: '25 mins ago (PlanetScope)',
      canopyChangeRate: '+0.4% Canopy Intactness',
      carbonCreditsIssued: 750000,
      vintage: 2025,
      description: 'Evergreen and semi-evergreen forest protecting Asian elephants and yellow-cheeked crested gibbons.',
      sensorMeshNodes: 105,
      droneSurveysCompleted: 33,
      traditionalAuditCost: 72000,
      traditionalAuditDays: 160,
      carbonProofCost: 3000,
      carbonProofSeconds: 3.9,
    },
    {
      id: 'CP-CDM-5510',
      name: 'Cardamom Mountains REDD+',
      location: 'Koh Kong Province',
      country: 'Cambodia',
      latitude: 11.542,
      longitude: 103.412,
      region: 'SE Asia',
      type: 'Avoided Deforestation',
      areaHectares: 445000,
      riskScore: 93,
      trustStatus: 'VERIFIED',
      lastScanDate: '14 mins ago (Sentinel-2B)',
      canopyChangeRate: '+0.7% Biomass Density',
      carbonCreditsIssued: 980000,
      vintage: 2025,
      description: 'Dense rainforest watershed protection connecting Cardamom National Parks against cashew plantation encroachment.',
      sensorMeshNodes: 125,
      droneSurveysCompleted: 42,
      traditionalAuditCost: 88000,
      traditionalAuditDays: 180,
      carbonProofCost: 3500,
      carbonProofSeconds: 4.1,
    },
    {
      id: 'CP-SMC-9901',
      name: 'Southern Cardamom Mangrove Belt',
      location: 'Sihanoukville Region',
      country: 'Cambodia',
      latitude: 10.812,
      longitude: 103.854,
      region: 'SE Asia',
      type: 'Mangrove Restoration',
      areaHectares: 42000,
      riskScore: 95,
      trustStatus: 'VERIFIED',
      lastScanDate: '35 mins ago (Sentinel-1 SAR)',
      canopyChangeRate: '+3.1% Blue Carbon Expansion',
      carbonCreditsIssued: 210000,
      vintage: 2025,
      description: 'Estuarine coastal mangrove planting buffering coral reef systems and marine biodiversity.',
      sensorMeshNodes: 60,
      droneSurveysCompleted: 20,
      traditionalAuditCost: 38000,
      traditionalAuditDays: 115,
      carbonProofCost: 1600,
      carbonProofSeconds: 3.2,
    },
  ];

  for (const projectData of projectsData) {
    const createdProject = await prisma.project.create({
      data: {
        ...projectData,
        credits: {
          create: [
            {
              id: `CP-2026-${projectData.id.split('-')[1]}-09412`,
              projectName: projectData.name,
              vintageYear: projectData.vintage,
              quantityTons: Math.round(projectData.carbonCreditsIssued * 0.1),
              serialNumber: `VCS-994-${projectData.vintage}-${projectData.id.split('-')[1]}-009412`,
              merkleRootHash: `0x${Math.random().toString(16).slice(2, 10)}${Math.random().toString(16).slice(2, 10)}${Math.random().toString(16).slice(2, 10)}`,
              verificationScore: projectData.riskScore,
              status: projectData.trustStatus === 'VERIFIED' ? 'VERIFIED & AUDITED' : 'FLAGGED FOR REVIEW',
              issueDate: 'October 14, 2025',
              owner: 'NatureCorp ESG Global Fund',
            },
          ],
        },
        telemetry: {
          create: [
            { date: 'Jan 2025', ndvi: 0.81, canopyDensity: 91.2, biomass: 240, radarBackscatter: -8.4, soilMoisture: 68, carbonFlux: 4.2 },
            { date: 'Feb 2025', ndvi: 0.82, canopyDensity: 91.5, biomass: 242, radarBackscatter: -8.3, soilMoisture: 71, carbonFlux: 4.3 },
            { date: 'Mar 2025', ndvi: 0.84, canopyDensity: 92.1, biomass: 244, radarBackscatter: -8.1, soilMoisture: 74, carbonFlux: 4.5 },
            { date: 'Apr 2025', ndvi: 0.85, canopyDensity: 92.4, biomass: 246, radarBackscatter: -8.0, soilMoisture: 72, carbonFlux: 4.6 },
            { date: 'May 2025', ndvi: 0.86, canopyDensity: 93.0, biomass: 248, radarBackscatter: -7.8, soilMoisture: 70, carbonFlux: 4.7 },
            { date: 'Jun 2025', ndvi: 0.87, canopyDensity: 93.4, biomass: 251, radarBackscatter: -7.7, soilMoisture: 69, carbonFlux: 4.8 },
            { date: 'Jul 2025', ndvi: 0.88, canopyDensity: 94.2, biomass: 254, radarBackscatter: -7.5, soilMoisture: 67, carbonFlux: 5.0 },
          ],
        },
        satelliteSnapshots: {
          create: [
            {
              date: '2024-08-15 (Baseline)',
              satellite: 'Sentinel-2A',
              resolution: '10m Multispectral',
              canopyDelta: 'Baseline Zero',
              imageUrl: 'https://images.unsplash.com/photo-1511497584788-8767611136f6?auto=format&fit=crop&w=800&q=80',
              ndviValue: 0.81,
              isBaseline: true,
            },
            {
              date: '2025-02-10',
              satellite: 'Sentinel-2B',
              resolution: '10m Multispectral',
              canopyDelta: '+0.6% Growth',
              imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
              ndviValue: 0.84,
            },
            {
              date: '2025-08-01 (Current)',
              satellite: 'Sentinel-2B + PlanetScope',
              resolution: '3m Sub-meter',
              canopyDelta: projectData.canopyChangeRate,
              imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
              ndviValue: 0.88,
            },
          ],
        },
        verificationLedger: {
          create: [
            {
              timestamp: new Date().toISOString(),
              title: 'Real-Time Sentinel-2B Optical Pass',
              source: 'Sentinel-2B Satellite',
              status: projectData.trustStatus === 'VERIFIED' ? 'VERIFIED' : 'WARNING',
              hash: `0x${Math.random().toString(16).slice(2, 10)}...${Math.random().toString(16).slice(2, 6)}`,
              description: `Multispectral canopy index verified across ${projectData.areaHectares.toLocaleString('en-US')} hectares. ${projectData.canopyChangeRate}.`,
            },
          ],
        },
        anomalies: {
          create: projectData.trustStatus !== 'VERIFIED'
            ? [
                {
                  timestamp: '12 mins ago',
                  projectName: projectData.name,
                  type: 'Canopy Loss',
                  severity: 'high',
                  status: 'ACTIVE',
                  details: `Localized canopy depression detected in Sector 7 via PlanetScope feed.`,
                  coordinates: `${Math.abs(projectData.latitude).toFixed(2)}°S ${Math.abs(projectData.longitude).toFixed(2)}°W`,
                },
              ]
            : [],
        },
      },
    });
  }

  console.log('Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
